_wandb:
    value:
        cli_version: 0.28.1
        e:
            36ixfkij4pe2plau586gq3sm9pmnzyqa:
                codePath: training/train_tensor.py
                codePathLocal: training/train_tensor.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "87991361536"
                        used: "34845573120"
                email: andreas.e.lindeman@gmail.com
                executable: /home/jadmin/miniconda3/envs/ml-env/bin/python3
                git:
                    commit: 74ccb17f6f3e0cf2ab6d734c532d49a34dd2bbe9
                    remote: https://github.com/andreasviner/ligmax-software.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-dc0eef2c-41e0-dd2f-8ab9-25b463d86b37
                host: jonastann-ubuntu
                memory:
                    total: "65427619840"
                os: Linux-7.0.0-28-generic-x86_64-with-glibc2.43
                program: /home/jadmin/Desktop/ligmax-software/training/train_tensor.py
                python: CPython 3.11.15
                root: /home/jadmin/Desktop/ligmax-software
                startedAt: "2026-07-19T14:51:29.680402Z"
                writerId: 36ixfkij4pe2plau586gq3sm9pmnzyqa
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.15
            "5": 0.28.1
            "10":
                - 20
            "12": 0.28.1
            "13": linux-x86_64
batch:
    value: 16
data:
    value: /home/jadmin/Desktop/ligmax-software/navier_merged/data_split.yaml
degrees:
    value: 8
device:
    value: ""
epochs:
    value: 150
fraction:
    value: 1
hsv_s:
    value: 0.75
hsv_v:
    value: 0.55
imgsz:
    value: 640
name:
    value: yolo26
patience:
    value: 0
perspective:
    value: 0.0008
project:
    value: /home/jadmin/Desktop/ligmax-software/runs/compare
scale:
    value: 0.55
seed:
    value: 0
shear:
    value: 2
sizes:
    value:
        - m
        - l
        - s
translate:
    value: 0.15
wandb_project:
    value: yolo26-architecture-comparison
