#!/usr/bin/env python3
"""
train_last2.py -- Two-phase YOLO26 size comparison for the Njord buoy detector.

Trains yolo26 m / n / s / l (m first: most important, then fastest-first so an
early cutoff still banks the small models). Each size is trained in TWO phases and
every model is streamed to Weights & Biases so it is retrievable later even if you
lose access to the training box.

    Phase 1 (base):     COCO-pretrained -> heavy augmentation + mosaic ON -> best.pt
    Phase 2 (finetune): load Phase-1 best.pt -> mosaic OFF (closed), low LR -> best.pt

Every problem this fixes vs train_last.py (go through them one by one):
  1. Missing size `n`               -> default sizes = m n s l (m first).
  2. Single-stage training          -> explicit two-phase base -> closed-mosaic finetune.
  3. Cloud weights never updated     -> `wandb.save(..., policy="live")` does not re-sync
     ("best.pt stuck at 17m ago"). Replaced by versioned W&B *artifacts* uploaded from
     an epoch callback + a clean final artifact per phase. Guaranteed retrievable.
  4. `scale=(0.25, 1)` tuple crash   -> Ultralytics treats `scale` as a single float
     fraction in [0,1] (cfg validation raises TypeError on a tuple). Use a float.
  5. Wrong classes (6 vs 3)          -> the labels are 3-class {green,red,cardinal} but
     data_split.yaml declares 6, so cardinal logs as "north" and e/s/w show 0 instances.
     This script generates a correct nc=3 split yaml at RUNTIME from train/val/test.txt
     (those + data_split.yaml are gitignored, so they must be fixed on the box itself).
  6. OOM / crashes                   -> multi_scale OFF by default (the 1.5x-scale OOM),
     deterministic=False (unstable 4090 kernels), phase-aware auto-resume, OOM batch
     backoff, CUDA cache cleared between runs. Safe to just re-launch after a crash.
  7. Heavy augmentation preserved    -> hsv/degrees/translate/scale/shear/perspective + mosaic.

Usage (on the GPU box, after `git pull`):
    python training/train_last2.py                 # all four sizes, full run
    python training/train_last2.py --sizes m       # just the important one
    python training/train_last2.py --batch 8       # if you still hit OOM
"""
import os
# Reduce allocator fragmentation (helps avoid OOM). setdefault so an explicit
# `export PYTORCH_CUDA_ALLOC_CONF=...` still wins. NOTE: this does NOT fix "unspecified
# launch failure" -- that is a kernel-launch/hardware fault, not a memory-pressure error.
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
import csv
import json
import argparse
import time
import gc
import sys
import traceback

import torch
import wandb


# ----------------------------------------------------------------------------- #
# Dataset config (fixes problem #5): build a correct 3-class split yaml at runtime.
# data_split.yaml + train/val/test.txt are gitignored, so we cannot ship a fixed
# one; instead we regenerate it on whatever machine trains, from the split lists
# that ARE present there. Falls back to the tracked data.yaml if lists are missing.
# ----------------------------------------------------------------------------- #
NAMES_3 = ["green", "red", "cardinal"]


def ensure_data_yaml(script_dir):
    root = os.path.abspath(os.path.join(script_dir, "..", "navier_merged"))
    train_txt = os.path.join(root, "train.txt")
    val_txt = os.path.join(root, "val.txt")
    test_txt = os.path.join(root, "test.txt")
    out = os.path.join(root, "data_split3.yaml")

    if os.path.exists(train_txt) and os.path.exists(val_txt):
        lines = [
            "# AUTO-GENERATED by train_last2.py -- 3-class split (green/red/cardinal).",
            "# Rebuilt every run from the (gitignored) train/val/test.txt lists so it is",
            "# always correct on whatever machine trains. 'path:' omitted on purpose ->",
            "# Ultralytics resolves paths relative to THIS file's own directory.",
            "train: train.txt",
            "val: val.txt",
        ]
        if os.path.exists(test_txt):
            lines.append("test: test.txt")
        lines += ["", "nc: 3", f"names: {NAMES_3}", ""]
        with open(out, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        print(f"[data] wrote 3-class split yaml -> {out}", flush=True)
        return out

    data_yaml = os.path.join(root, "data.yaml")
    if os.path.exists(data_yaml):
        print("[data] WARNING: train.txt/val.txt not found; falling back to data.yaml "
              "(train==val, so val metrics will be optimistic).", flush=True)
        return data_yaml
    raise SystemExit(f"[data] no dataset config found under {root}")


def sanity_check_labels(data_yaml, nc=3, sample=25):
    """Best-effort, fast: warn loudly if labels still carry class ids >= nc (i.e. the
    6-class labels were not remapped on this box -> run training/remap_6to3.py)."""
    try:
        root = os.path.dirname(os.path.abspath(data_yaml))
        train_txt = os.path.join(root, "train.txt")
        if not os.path.exists(train_txt):
            return
        with open(train_txt, encoding="utf-8") as f:
            imgs = [ln.strip() for ln in f if ln.strip()][:sample]
        worst = -1
        for img in imgs:
            lbl = os.path.join(root, img).replace("\\", "/")
            lbl = lbl.replace("/images/", "/labels/").rsplit(".", 1)[0] + ".txt"
            if not os.path.exists(lbl):
                continue
            with open(lbl, encoding="utf-8") as lf:
                for line in lf:
                    p = line.split()
                    if p:
                        worst = max(worst, int(p[0]))
        if worst >= nc:
            print(f"\n[labels] !!! WARNING: found class id {worst} but nc={nc}. Your "
                  f"labels look like the 6-class set. Run:  python training/remap_6to3.py"
                  f"  on this box, then re-launch.\n", flush=True)
        else:
            print(f"[labels] sample OK: max class id = {worst} (< nc={nc})", flush=True)
    except Exception as e:
        print(f"[labels] sanity check skipped ({type(e).__name__}: {e})", flush=True)


def get_device(arg):
    if arg:
        return arg
    return "0" if torch.cuda.is_available() else "cpu"


def empty_cuda():
    try:
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
    except Exception:
        pass  # context may be corrupt after a CUDA fault; never mask the real error


# Exit code that run_loop.sh watches for to restart a FRESH process after a GPU crash.
CUDA_FAULT_EXIT = 75


def is_cuda_fault(e):
    """True for CUDA faults that CORRUPT the context -> unrecoverable in-process, the whole
    process must restart (that is what run_loop.sh does). OOM is excluded on purpose: it is
    recoverable and handled by the batch backoff."""
    if isinstance(e, torch.cuda.OutOfMemoryError):
        return False
    s = f"{type(e).__name__}: {e}".lower()
    return any(k in s for k in (
        "unspecified launch failure", "illegal memory access", "device-side assert",
        "cuda error", "acceleratorerror", "cublas", "cudnn status",
        "misaligned address", "an illegal instruction",
    ))


# ----------------------------------------------------------------------------- #
# Crash-safety helpers
# ----------------------------------------------------------------------------- #
def best_or_last(run_dir):
    b = os.path.join(run_dir, "weights", "best.pt")
    return b if os.path.exists(b) else os.path.join(run_dir, "weights", "last.pt")


def phase_finished(run_dir):
    """True iff this phase TRULY completed. Ultralytics' strip_optimizer rewrites the final
    last.pt to epoch == -1 when a run finishes; an interrupted run keeps epoch >= 0. We read
    that single field instead of a marker file, because a crash could otherwise leave a bogus
    'done' marker (that exact bug sent a run straight to finetuning). Safe-fails to False
    (-> we just resume/retry) if the checkpoint can't be read."""
    last = os.path.join(run_dir, "weights", "last.pt")
    if not os.path.exists(last):
        return False
    try:
        ck = torch.load(last, map_location="cpu", weights_only=False)
        return int(ck.get("epoch", 0)) == -1
    except Exception:
        return False


def resume_is_stale(run_dir, start_weights):
    """True if this phase's last.pt predates its start weights -- i.e. the inputs were
    (re)generated after our checkpoint, so resuming would continue from an outdated base.
    Used for phase 2: if phase 1 was re-run, its best.pt is newer than a stale finetune
    checkpoint, so we restart phase 2 fresh from the correct base instead of resuming."""
    last = os.path.join(run_dir, "weights", "last.pt")
    sw = str(start_weights)
    try:
        return (os.path.exists(last) and os.path.exists(sw)
                and os.path.getmtime(sw) > os.path.getmtime(last))
    except Exception:
        return False


def wandb_init_resumable(project, name, group, job_type, config, run_dir):
    """One W&B run per phase, resumable across restarts (same run id survives a crash)."""
    os.makedirs(run_dir, exist_ok=True)
    id_file = os.path.join(run_dir, "wandb_id.txt")
    run_id = None
    if os.path.exists(id_file):
        run_id = (open(id_file, encoding="utf-8").read().strip() or None)
    if run_id is None:
        run_id = wandb.util.generate_id()
        with open(id_file, "w", encoding="utf-8") as f:
            f.write(run_id)
    return wandb.init(project=project, name=name, group=group, job_type=job_type,
                      config=config, id=run_id, resume="allow", reinit=True)


def upload_artifact(run, art_name, path, metadata=None):
    """Upload a single weights file as a versioned model artifact (crash-proof cloud copy)."""
    try:
        if not (path and os.path.exists(path)):
            return
        art = wandb.Artifact(art_name, type="model", metadata=metadata or {})
        art.add_file(str(path))
        run.log_artifact(art)
        print(f"[wandb] uploaded artifact '{art_name}' <- {os.path.basename(path)}", flush=True)
    except Exception as e:  # never let a W&B hiccup kill training
        print(f"[wandb] artifact upload failed (non-fatal): {type(e).__name__}: {e}", flush=True)


def make_ckpt_callback(run, sz, phase_tag, ckpt_every):
    """on_fit_epoch_end: log epoch metrics to W&B and push best/last.pt as an artifact.
    THIS is the real fix for weights never updating in the cloud. Uploads after the FIRST
    completed epoch of every run -- fresh OR resume (immediate confirmation + earliest
    safety net), then every `ckpt_every` epochs, then the final epoch -- so a downloadable
    model exists almost from the start and refreshes right after any restart, not just at
    the end. Each upload is a new version of the same artifact; download the 'latest'."""
    art_name = f"yolo26{sz}-{phase_tag}-ckpt"
    state = {"uploaded": False}  # force an upload on the first epoch after any (re)start

    def cb(trainer):
        try:
            epoch = int(getattr(trainer, "epoch", 0)) + 1
            total = int(getattr(trainer, "epochs", 0) or 0)

            logd = {}
            # validation metrics (mAP50-95/mAP50, precision, recall, val losses)
            for k, v in (getattr(trainer, "metrics", None) or {}).items():
                try:
                    logd[k] = float(v)
                except Exception:
                    pass
            # training losses (box/cls/dfl) -- richer charts
            try:
                tl = getattr(trainer, "tloss", None)
                if tl is not None:
                    for k, v in trainer.label_loss_items(tl, prefix="train").items():
                        logd[k] = float(v)
            except Exception:
                pass
            # learning rate(s)
            try:
                for k, v in (getattr(trainer, "lr", None) or {}).items():
                    logd[k] = float(v)
            except Exception:
                pass
            if logd:
                logd["epoch"] = epoch
                run.log(logd, step=epoch)

            is_last = total and epoch >= total
            first = not state["uploaded"]  # first completed epoch of THIS run (fresh/resume)
            if first or (ckpt_every and epoch % ckpt_every == 0) or is_last:
                art = wandb.Artifact(art_name, type="model", metadata={"epoch": epoch})
                added = False
                for p in (getattr(trainer, "best", None), getattr(trainer, "last", None)):
                    if p and os.path.exists(str(p)):
                        art.add_file(str(p))
                        added = True
                if added:
                    run.log_artifact(art)
                    state["uploaded"] = True
                    print(f"[wandb] checkpoint artifact '{art_name}' @ epoch {epoch} "
                          f"(download the 'latest' version)", flush=True)
        except Exception as e:  # non-fatal by design
            print(f"[wandb-cb] non-fatal: {type(e).__name__}: {e}", flush=True)

    return cb


def train_with_oom_backoff(start_weights, train_kwargs, callbacks, batch, min_batch):
    """Fresh training with automatic batch halving on CUDA OOM (fixes problem #6).
    Rebuilds the model each attempt because trainer state is unusable after an OOM."""
    b = batch
    while True:
        try:
            model = YOLO(start_weights)
            for ev, fn in callbacks.items():
                model.add_callback(ev, fn)
            kw = dict(train_kwargs)
            kw["batch"] = b
            model.train(**kw)
            return model
        except (torch.cuda.OutOfMemoryError, RuntimeError) as e:
            is_oom = isinstance(e, torch.cuda.OutOfMemoryError) or "out of memory" in str(e).lower()
            if not is_oom:
                raise
            empty_cuda()
            if b <= min_batch:
                print(f"[OOM] still OOM at floor batch={b}; re-raising.", flush=True)
                raise
            nb = max(min_batch, b // 2)
            print(f"[OOM] CUDA out of memory at batch={b} -> retrying at batch={nb}.", flush=True)
            b = nb


def do_phase(phase_tag, sz, run_dir, start_weights, train_kwargs, args, resume_ok=True):
    """Run one training phase: resumable W&B run + per-epoch checkpoint artifacts +
    resume-or-fresh(with OOM backoff). Returns path to the phase's best.pt."""
    run_name = os.path.basename(run_dir)
    if phase_finished(run_dir):
        print(f">>> {run_name}: already complete (checkpoint epoch=-1) -- skipping.", flush=True)
        return best_or_last(run_dir)

    run = wandb_init_resumable(
        project=args.wandb_project, name=run_name,
        group=f"{args.name}_{sz}", job_type=phase_tag,
        config={**vars(args), "phase": phase_tag, "size": sz,
                "start_weights": os.path.basename(str(start_weights))},
        run_dir=run_dir)
    try:
        callbacks = {"on_fit_epoch_end": make_ckpt_callback(run, sz, phase_tag, args.ckpt_every)}
        last = os.path.join(run_dir, "weights", "last.pt")
        stale = resume_is_stale(run_dir, start_weights)
        if stale:
            print(f">>> {run_name}: last.pt is older than its start weights -> discarding "
                  f"stale checkpoint and restarting this phase fresh.", flush=True)

        if resume_ok and os.path.exists(last) and not stale:
            print(f">>> RESUME {run_name} from {last}", flush=True)
            model = YOLO(last)
            for ev, fn in callbacks.items():
                model.add_callback(ev, fn)
            try:
                model.train(resume=True)  # uses the checkpoint's saved args
            except Exception as re:
                if is_cuda_fault(re):
                    raise  # a GPU crash is NOT "complete" -- propagate so the run restarts
                msg = str(re).lower()
                if "nothing to resume" in msg or "is finished" in msg or phase_finished(run_dir):
                    print(f"[resume] {run_name} already finished -- skipping to eval.", flush=True)
                else:
                    raise  # a real error -- do NOT mask it as 'complete'
        else:
            train_with_oom_backoff(start_weights, train_kwargs, callbacks,
                                   args.batch, args.min_batch)

        best = best_or_last(run_dir)
        upload_artifact(run, f"yolo26{sz}-{phase_tag}", best,
                        metadata={"size": sz, "phase": phase_tag})
        return best
    finally:
        run.finish()
        empty_cuda()


# ----------------------------------------------------------------------------- #
def main():
    ap = argparse.ArgumentParser()
    script_dir = os.path.dirname(os.path.abspath(__file__))
    ap.add_argument("--data", default="",
                    help="data yaml; default = auto-generated 3-class split.")
    # m first (most important), then fastest-first so a cutoff still banks the small ones.
    ap.add_argument("--sizes", nargs="+", default=["m", "n", "s", "l"])
    ap.add_argument("--epochs1", type=int, default=120, help="phase-1 (base) epochs")
    ap.add_argument("--epochs2", type=int, default=30, help="phase-2 (finetune) epochs")
    ap.add_argument("--imgsz", type=int, default=640)
    # Fixed batch (NOT autobatch): safe for m/n/s/l on 24 GB. OOM backoff halves it if needed.
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--min_batch", type=int, default=2, help="OOM-backoff floor")
    ap.add_argument("--device", default="")
    ap.add_argument("--fraction", type=float, default=1.0)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--patience", type=int, default=0)   # 0 => no early stop (train full)
    # Ubuntu box: workers>0 is fine and important here (heavy CPU-side augmentation would
    # starve the GPU at workers=0). If you ever get an epoch-boundary hang: on Linux that
    # is usually W&B (try WANDB_START_METHOD=thread) or, in Docker, too-small /dev/shm
    # (use --ipc=host or a bigger shm) -- lower this only as a last resort.
    ap.add_argument("--workers", type=int, default=8,
                    help="dataloader workers (Linux: 8 is fine; lower only if you hit an "
                         "epoch-boundary hang and W&B/shm fixes don't help).")
    ap.add_argument("--ckpt_every", type=int, default=10,
                    help="upload best/last.pt to W&B every N epochs (crash safety); "
                         "also always uploads at epoch 1 and the final epoch")
    ap.add_argument("--ft_lr0", type=float, default=0.005, help="phase-2 initial LR")
    # multi_scale OFF by default: the +/-scale up to 1.5x imgsz is what OOM'd before.
    # It is a FLOAT fraction in this Ultralytics (True==1.0), NOT a bool.
    ap.add_argument("--multi_scale", type=float, default=0.0)
    # Heavy augmentation (preserved). scale is a single float: range = [1-scale, 1+scale].
    ap.add_argument("--hsv_s", type=float, default=0.75)     # sun washout
    ap.add_argument("--hsv_v", type=float, default=0.55)     # sun/overexposure
    ap.add_argument("--degrees", type=float, default=8.0)    # boat roll / edge tilt
    ap.add_argument("--translate", type=float, default=0.15)
    ap.add_argument("--scale", type=float, default=0.6)      # [0.4, 1.6]; raise toward
    #                                                          0.75 for more tiny far buoys
    ap.add_argument("--shear", type=float, default=2.0)
    ap.add_argument("--perspective", type=float, default=0.0008)  # closest lever to fisheye
    ap.add_argument("--project", default=os.path.abspath(
        os.path.join(script_dir, "..", "runs", "compare")))
    ap.add_argument("--name", default="yolo26")
    ap.add_argument("--wandb_project", default="njord-yolo26-3class")
    args = ap.parse_args()

    global YOLO
    from ultralytics import YOLO
    from ultralytics.utils.torch_utils import get_flops
    # We drive W&B ourselves (one run per phase); disable the native integration so we
    # don't get duplicate runs / step collisions across the two train() calls.
    try:
        from ultralytics import settings as ul_settings
        ul_settings.update({"wandb": False})
    except Exception as e:
        print(f"[settings] could not disable native ultralytics W&B: {e}", flush=True)

    data_yaml = args.data or ensure_data_yaml(script_dir)
    sanity_check_labels(data_yaml, nc=len(NAMES_3))

    device = get_device(args.device)
    print(f"[train_last2] device={device} sizes={args.sizes} "
          f"epochs={args.epochs1}+{args.epochs2} imgsz={args.imgsz} "
          f"batch={args.batch} data={data_yaml}", flush=True)
    if device == "cpu":
        print("[train_last2] WARNING: running on CPU -- this is built for a CUDA GPU.", flush=True)

    os.makedirs(args.project, exist_ok=True)
    results_dir = os.path.join(args.project, "_summary")
    os.makedirs(results_dir, exist_ok=True)
    csv_path = os.path.join(results_dir, "compare_results.csv")
    json_path = os.path.join(results_dir, "compare_results.json")
    rows, names = [], None
    # Reload prior results so the summary stays complete AND finished sizes are skipped
    # across run_loop.sh restarts (crucial on a flaky GPU that restarts many times).
    if os.path.exists(json_path):
        try:
            prev = json.load(open(json_path, encoding="utf-8"))
            rows = prev.get("rows", []) or []
            names = prev.get("class_names") or None
        except Exception:
            pass
    done_models = {r.get("model") for r in rows if r and "error" not in r}

    common = dict(
        data=data_yaml, imgsz=args.imgsz, device=device, seed=args.seed,
        deterministic=False, fraction=args.fraction, patience=args.patience,
        project=args.project, exist_ok=True, plots=True, verbose=True,
        workers=args.workers,
        hsv_s=args.hsv_s, hsv_v=args.hsv_v, degrees=args.degrees,
        translate=args.translate, shear=args.shear, perspective=args.perspective,
    )

    for sz in args.sizes:
        if f"yolo26{sz}" in done_models:
            print(f">>> yolo26{sz} already complete (in summary) -- skipping.", flush=True)
            continue
        print(f"\n{'='*64}\n>>> yolo26{sz}  (phase 1 base -> phase 2 finetune)\n{'='*64}", flush=True)
        t0 = time.time()
        group = f"{args.name}_{sz}"
        p1_dir = os.path.join(args.project, f"{group}_p1base")
        p2_dir = os.path.join(args.project, f"{group}_p2ft")
        try:
            # -------- Phase 1: base training, heavy aug + mosaic ON --------
            p1_kwargs = dict(common, epochs=args.epochs1, name=f"{group}_p1base",
                             multi_scale=args.multi_scale, scale=args.scale,
                             mosaic=1.0, close_mosaic=0)
            p1_best = do_phase("base", sz, p1_dir, f"yolo26{sz}.pt", p1_kwargs, args)

            # -------- Phase 2: closed-mosaic finetune from Phase-1 best --------
            p2_kwargs = dict(common, epochs=args.epochs2, name=f"{group}_p2ft",
                             multi_scale=0.0, scale=min(args.scale, 0.5),
                             mosaic=0.0, close_mosaic=0,
                             lr0=args.ft_lr0, warmup_epochs=1.0, cos_lr=True,
                             degrees=args.degrees * 0.5, shear=args.shear * 0.5,
                             perspective=args.perspective * 0.5)
            final_best = do_phase("finetune", sz, p2_dir, p1_best, p2_kwargs, args,
                                  resume_ok=True)

            # -------- Eval final model + log comparison row --------
            eval_run = wandb_init_resumable(
                project=args.wandb_project, name=f"{group}_eval",
                group=group, job_type="eval",
                config={"size": sz, "phase": "eval"}, run_dir=os.path.join(args.project, f"{group}_eval"))
            try:
                ev = YOLO(final_best)
                m = ev.val(data=data_yaml, imgsz=args.imgsz, device=device, split="val",
                           project=args.project, name=f"{group}_val", exist_ok=True, verbose=False)
                names = getattr(m, "names", None) or names
                params = sum(p.numel() for p in ev.model.parameters())
                try:
                    flops = get_flops(ev.model, args.imgsz)
                except Exception:
                    flops = float("nan")
                sp = m.speed
                row = {
                    "model": f"yolo26{sz}", "params_M": round(params / 1e6, 3),
                    "GFLOPs": round(flops, 2) if flops == flops else None,
                    "mAP50-95": round(float(m.box.map), 5),
                    "mAP50": round(float(m.box.map50), 5),
                    "precision": round(float(m.box.mp), 5),
                    "recall": round(float(m.box.mr), 5),
                    "infer_ms": round(float(sp.get("inference", float("nan"))), 3),
                    "total_ms": round(sum(sp.values()), 3),
                    "train_min": round((time.time() - t0) / 60, 2),
                    "epochs": args.epochs1 + args.epochs2, "imgsz": args.imgsz, "device": device,
                    "per_class_mAP50-95": [round(float(x), 4) for x in list(m.box.maps)],
                }
                rows.append(row)
                print(f"[done] {row}", flush=True)
                eval_run.log({f"summary/{k}": v for k, v in row.items()
                              if isinstance(v, (int, float))})
                # one clean, easy-to-find final model per size
                upload_artifact(eval_run, f"yolo26{sz}-final", final_best,
                                metadata={"size": sz, **{k: row[k] for k in ("mAP50-95", "mAP50")}})
            finally:
                eval_run.finish()
                empty_cuda()

        except Exception as e:
            if is_cuda_fault(e):
                print(f"\n[FATAL] CUDA fault in yolo26{sz}: {type(e).__name__}: {e}\n"
                      f"        Context is corrupted; exiting {CUDA_FAULT_EXIT} so run_loop.sh\n"
                      f"        restarts a FRESH process (resumes from last.pt, skips finished).",
                      flush=True)
                _persist(csv_path, json_path, rows, names)
                empty_cuda()
                sys.exit(CUDA_FAULT_EXIT)
            traceback.print_exc()
            rows.append({"model": f"yolo26{sz}", "error": f"{type(e).__name__}: {e}"})
        finally:
            empty_cuda()

        _persist(csv_path, json_path, rows, names)  # incremental: survive a mid-run crash

    _persist(csv_path, json_path, rows, names)
    print(f"\n[train_last2] summary -> {csv_path}", flush=True)


def _flush(csv_path, rows, names):
    base = ["model", "params_M", "GFLOPs", "mAP50-95", "mAP50", "precision",
            "recall", "infer_ms", "total_ms", "train_min", "epochs", "imgsz",
            "device", "per_class_mAP50-95", "error"]
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=base)
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in base})


def _persist(csv_path, json_path, rows, names):
    """Write CSV + JSON summary. JSON is reloaded on restart to skip finished sizes."""
    _flush(csv_path, rows, names)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump({"class_names": names, "rows": rows}, f, indent=2)


if __name__ == "__main__":
    main()
